# Generated by Django 2.2.4 on 2020-07-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200731_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='l_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='m_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='s_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='size_l',
        ),
        migrations.RemoveField(
            model_name='item',
            name='size_m',
        ),
        migrations.RemoveField(
            model_name='item',
            name='size_s',
        ),
        migrations.RemoveField(
            model_name='item',
            name='size_xl',
        ),
        migrations.RemoveField(
            model_name='item',
            name='xl_price',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
